Setup live demo + first update with Smart actions prefilled with a specific value
ForestAdmin/forest-live-demo-rails pull request #2
Opened 2018-05-31 15:27 UTC by Tolsa

2018-05-31 15:29 UTC, Tolsa commented on config/routes.rb
> +    post '/actions/charge-credit-card/values' => 'customers#charge_credit_card_values'
This needs to be kept for Smart action with prefilled value

2018-06-01 13:56 UTC, SeyZ requested changes

2018-06-01 13:56 UTC, SeyZ commented on Gemfile
> +gem 'forest_liana'
Already exists, please remove this.

2018-06-01 13:56 UTC, SeyZ commented on config/database.yml
> +  database: forest-live-demo-rails_development
Should not change

2018-06-01 13:56 UTC, SeyZ commented on config/initializers/forest_liana.rb
> -}
Why do you remove the Stripe integration?

2018-06-01 13:56 UTC, SeyZ commented on config/secrets.yml
> +  forest_env_secret: e209866f811fa84105cfa2db6d20eabd8fc598fdfdedb864b61816f6c90449ae
Pas changé

2018-06-01 13:56 UTC, SeyZ commented on db/schema.rb
>  end
should not change at all

2018-06-04 08:44 UTC, closed without merging